//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JVStoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDesc { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> ESRBID { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public int MediaID { get; set; }
        public int StockStatusID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string GameImage { get; set; }
        public Nullable<int> UnitsSold { get; set; }
    
        public virtual ESRB ESRB { get; set; }
        public virtual MediaType MediaType { get; set; }
        public virtual NumPlayer NumPlayer { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual StockStatus StockStatus { get; set; }
    }
}
